### PR TITLE
New trophy

### PR DESCRIPTION
**Pull request by HydraDragonAntivirus**
1.8+ million line human YARA rules 3+ million line non human YARA rules

### CODE REVIEW

**Comment by HydraDragonAntivirus** [comment]
Also I can share my malware samples and benign samples to train and test your YARA rules.

**Comment by JosiahRaySmith** [comment]
The URL is linked to clara and not https://github.com/HydraDragonAntivirus/Hydra-Dragon-Antivirus-Linux...

**Comment by HydraDragonAntivirus** [comment]
https://github.com/HydraDragonAntivirus/HydraDragonAntivirus

**Comment by HydraDragonAntivirus** [comment]
oops let me fix

**Pull request merged**
